openapi: 3.0.3
info:
  info:
  version: 1.0.0
  title: Simple Artist API
  description: A simple API to illustrate OpenAPI concepts
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /news/count:
    get:
      summary: Get total news counter
      tags:
        - News
      responses:
        200:
          description: Successful response with the total news counter
          schema:
            type: object
            properties:
              count:
                type: integer
                description: The total count of news items

  /news:
    get:
      summary: Get news items
      tags:
        - News
      parameters:
        - in: query
          name: list
          type: integer
          description: Number of news items to retrieve
      responses:
        200:
          description: A list of news items

    post:
      summary: Save a single news item
      tags:
        - News
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: titular
          type: string
          description: The title of the news
        - in: formData
          name: descripcion
          type: string
          description: The description of the news
        - in: formData
          name: noticia
          type: string
          description: The news content
        - in: formData
          name: redactor
          type: string
          description: The author of the news
        - in: formData
          name: provincia
          type: string
          description: The province of the news
      responses:
        201:
          description: News item created successfully
        400:
          description: Bad request

  /news/{id}:
    get:
      summary: Get single news by ID
      tags:
        - News
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the news item to retrieve
      responses:
        200:
          description: Successful response with the requested news item
          schema:
            type: object
            properties:
              id:
                type: integer
                description: The ID of the news item
              titular:
                type: string
                description: The title of the news
              descripcion:
                type: string
                description: The description of the news
              noticia:
                type: string
                description: The news content
              redactor:
                type: string
                description: The author of the news
              provincia:
                type: string
                description: The province of the news
        404:
          description: News item not found

    put:
      summary: Update a single news item by ID
      tags:
        - News
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the news item to update
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              titular:
                type: string
                description: The updated title of the news
              descripcion:
                type: string
                description: The updated description of the news
              noticia:
                type: string
                description: The updated news content
              redactor:
                type: string
                description: The updated author of the news
              provincia:
                type: string
                description: The updated province of the news
      responses:
        204:
          description: News item updated successfully
        400:
          description: Bad request
        404:
          description: News item not found

    delete:
      summary: Delete a single news item by ID
      tags:
        - News
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the news item to delete
      responses:
        204:
          description: News item deleted successfully
        404:
          description: News item not found
